### ISSUE TITLE
MongoDB Connection Issue

### ISSUE THREAD

**Issue by shayk89** [bytesizedxyz/nov-project-chirp-backend#12]
`
Nov 21 09:08:53 nov-chirp-backend app/web.1: Mongoose's are running around on port 45202 
Nov 21 09:08:53 nov-chirp-backend app/web.1: { MongoNetworkError: connection 5 to nov-chirp-backend-shard-00-01-ap0s9.mongodb.net:27017 closed 
Nov 21 09:08:53 nov-chirp-backend app/web.1:     at TLSSocket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:276:9) 
Nov 21 09:08:53 nov-chirp-backend app/web.1:     at Object.onceWrapper (events.js:273:13) 
Nov 21 09:08:53 nov-chirp-backend app/web.1:     at TLSSocket.emit (events.js:187:15) 
Nov 21 09:08:53 nov-chirp-backend app/web.1:     at _handle.close (net.js:606:12) 
Nov 21 09:08:53 nov-chirp-backend app/web.1:     at TCP.done (_tls_wrap.js:386:7) 
Nov 21 09:08:53 nov-chirp-backend app/web.1:   name: 'MongoNetworkError', 
Nov 21 09:08:53 nov-chirp-backend app/web.1:   errorLabels: [ 'TransientTransactionError' ], 
Nov 21 09:08:53 nov-chirp-backend app/web.1:   [Symbol(mongoErrorContextSymbol)]: {} } 
`
Not sure if you need to make sure the database is running or if you need to whitelist an ip for access

**Comment by signalnerve** [comment]
hey, looking!

**Comment by signalnerve** [comment]
just going to whitelist all ips for now :)
