### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by signalnerve** [bytesizedxyz/nov-project-chirp-backend#28]
Changes to be implemented:
expected Comment Structure from the client:
 { comment: '', chirpId: '' }
HTTP Header - Authorization: "JWT Bearer Token"
POST route: https://nov-chirp-backend.herokuapp.com/chirp/comment/

GET all chirps - returns all chirps and associated comments in an array attached to comment

**Comment by signalnerve** [comment]
need to meet w/ frontend on this, briefly

**Comment by shayk89** [comment]
@maverickg59 
post {comment:"", chirpId:""} to /chirp/comment/
response will look like -  data:{comment:"", chirpId:"", createdAt:Date, username:""}
NOT live yet. Still need to set it up so you get comments with chirps

**Comment by maverickg59** [comment]
Shay I just realized we need user email to produce profile image. Please add property "email" to data object.
